"""
Manual graph implementation for EduStruct.

This module models course prerequisite maps using an adjacency-list graph.
It is intentionally independent from Flask, serializers, services, routes,
and external graph libraries. The implementation is designed for educational
visualization of DFS and BFS traversals.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Any, Optional

try:
    from .queue import Queue
    from .stack import Stack
except ImportError:  # Allows direct execution in isolated unit tests.
    from queue import Queue
    from stack import Stack


@dataclass
class GraphNode:
    """Vertex stored in a manual adjacency-list graph."""

    id: str
    value: Any
    neighbors: list[str] = field(default_factory=list)

    def degree(self) -> int:
        """Return outgoing degree for this node."""
        return len(self.neighbors)

    def to_dict(self) -> dict[str, Any]:
        """Serialize the node without exposing object references."""
        return {
            "id": self.id,
            "value": self.value,
            "neighbors": list(self.neighbors),
            "degree": self.degree(),
        }


@dataclass
class GraphSearchResult:
    """Detailed search result for a graph node."""

    found: bool
    node_id: str
    node: Optional[GraphNode] = None
    comparisons: int = 0

    def to_dict(self) -> dict[str, Any]:
        """Serialize the search result to a JSON-friendly dictionary."""
        return {
            "found": self.found,
            "nodeId": self.node_id,
            "node": self.node.to_dict() if self.node else None,
            "comparisons": self.comparisons,
        }


@dataclass
class GraphTraversalStep:
    """Single visual step generated by DFS or BFS."""

    step: int
    action: str
    node_id: str
    visited_order: list[str] = field(default_factory=list)
    frontier: list[str] = field(default_factory=list)
    edge: Optional[tuple[str, str]] = None

    def to_dict(self) -> dict[str, Any]:
        """Serialize traversal metadata for future animation layers."""
        return {
            "step": self.step,
            "action": self.action,
            "nodeId": self.node_id,
            "visitedOrder": list(self.visited_order),
            "frontier": list(self.frontier),
            "edge": {"source": self.edge[0], "target": self.edge[1]} if self.edge else None,
        }


@dataclass
class GraphTraversalResult:
    """Traversal result with order and animation steps."""

    algorithm: str
    start_node_id: str
    order: list[str]
    steps: list[GraphTraversalStep]

    def to_dict(self) -> dict[str, Any]:
        """Serialize traversal result."""
        return {
            "algorithm": self.algorithm,
            "startNodeId": self.start_node_id,
            "order": list(self.order),
            "steps": [step.to_dict() for step in self.steps],
        }


class Graph:
    """
    Directed graph implemented with an adjacency list.

    For EduStruct prerequisite maps, edges should normally be inserted as:
    ``prerequisite_course_id -> dependent_course_id``. This direction makes
    DFS/BFS demonstrate how knowledge unlocks later courses.
    """

    def __init__(self, directed: bool = True) -> None:
        if not isinstance(directed, bool):
            raise ValueError("DIRECTED_MUST_BE_BOOLEAN")
        self._directed = directed
        self._adjacency_list: dict[str, GraphNode] = {}
        self._edges_count = 0
        self._last_operation: Optional[dict[str, Any]] = None

    @property
    def directed(self) -> bool:
        """Return True when the graph stores directed edges."""
        return self._directed

    @property
    def adjacency_list(self) -> dict[str, GraphNode]:
        """Return the node map used by serializers and tests."""
        return self._adjacency_list

    @property
    def vertices_count(self) -> int:
        """Return the number of vertices."""
        return len(self._adjacency_list)

    @property
    def edges_count(self) -> int:
        """Return the number of logical edges."""
        return self._edges_count

    @property
    def last_operation(self) -> Optional[dict[str, Any]]:
        """Return metadata for the most recent operation."""
        if self._last_operation is None:
            return None
        return dict(self._last_operation)

    def is_empty(self) -> bool:
        """Return True when the graph has no vertices."""
        return self.vertices_count == 0

    def add_node(self, node_id: Any, value: Any = None) -> GraphNode:
        """Insert a graph node with a stable identifier."""
        normalized_id = self._normalize_node_id(node_id)
        if normalized_id in self._adjacency_list:
            raise ValueError("DUPLICATE_NODE")

        node = GraphNode(id=normalized_id, value=value if value is not None else normalized_id)
        self._adjacency_list[normalized_id] = node
        self._last_operation = {
            "operation": "ADD_NODE",
            "nodeId": normalized_id,
            "verticesCount": self.vertices_count,
            "edgesCount": self.edges_count,
        }
        return node

    def add_edge(self, source_id: Any, target_id: Any) -> tuple[str, str]:
        """
        Insert an edge between two existing nodes.

        Duplicate edges are rejected to keep traversal and visualization output
        deterministic. In undirected mode, the reverse neighbor is maintained
        automatically while the logical edge count increases only once.
        """
        source = self._normalize_node_id(source_id)
        target = self._normalize_node_id(target_id)
        if source == target:
            raise ValueError("SELF_LOOPS_NOT_ALLOWED")
        if source not in self._adjacency_list:
            raise ValueError("SOURCE_NODE_NOT_FOUND")
        if target not in self._adjacency_list:
            raise ValueError("TARGET_NODE_NOT_FOUND")
        if target in self._adjacency_list[source].neighbors:
            raise ValueError("DUPLICATE_EDGE")

        self._adjacency_list[source].neighbors.append(target)
        if not self._directed:
            self._adjacency_list[target].neighbors.append(source)
        self._edges_count += 1
        self._last_operation = {
            "operation": "ADD_EDGE",
            "source": source,
            "target": target,
            "directed": self._directed,
            "verticesCount": self.vertices_count,
            "edgesCount": self.edges_count,
        }
        return source, target

    def search(self, node_id: Any) -> GraphSearchResult:
        """Search a node by id and return metadata."""
        normalized_id = self._normalize_node_id(node_id)
        comparisons = 0
        for current_id, node in self._adjacency_list.items():
            comparisons += 1
            if current_id == normalized_id:
                result = GraphSearchResult(True, normalized_id, node=node, comparisons=comparisons)
                self._last_operation = {
                    "operation": "SEARCH",
                    "nodeId": normalized_id,
                    "found": True,
                    "comparisons": comparisons,
                }
                return result

        result = GraphSearchResult(False, normalized_id, comparisons=comparisons)
        self._last_operation = {
            "operation": "SEARCH",
            "nodeId": normalized_id,
            "found": False,
            "comparisons": comparisons,
        }
        return result

    def contains(self, node_id: Any) -> bool:
        """Return True when a node exists."""
        return self.search(node_id).found

    def dfs(self, start_node_id: Any) -> GraphTraversalResult:
        """Execute iterative depth-first search from a start node."""
        start = self._validate_start_node(start_node_id)
        visited: set[str] = set()
        order: list[str] = []
        steps: list[GraphTraversalStep] = []
        stack = Stack()
        stack.push(start)
        step_index = 0

        while not stack.is_empty():
            current = stack.pop()
            if current in visited:
                continue

            visited.add(current)
            order.append(current)
            steps.append(
                GraphTraversalStep(
                    step=step_index,
                    action="VISIT",
                    node_id=current,
                    visited_order=list(order),
                    frontier=stack.to_list(),
                )
            )
            step_index += 1

            neighbors = self._adjacency_list[current].neighbors
            for neighbor in reversed(neighbors):
                if neighbor not in visited:
                    stack.push(neighbor)
                    steps.append(
                        GraphTraversalStep(
                            step=step_index,
                            action="DISCOVER",
                            node_id=neighbor,
                            visited_order=list(order),
                            frontier=stack.to_list(),
                            edge=(current, neighbor),
                        )
                    )
                    step_index += 1

        result = GraphTraversalResult("DFS", start, order, steps)
        self._last_operation = {
            "operation": "DFS",
            "startNodeId": start,
            "visitedCount": len(order),
            "order": list(order),
        }
        return result

    def bfs(self, start_node_id: Any) -> GraphTraversalResult:
        """Execute breadth-first search from a start node."""
        start = self._validate_start_node(start_node_id)
        visited: set[str] = {start}
        order: list[str] = []
        steps: list[GraphTraversalStep] = []
        queue = Queue()
        queue.enqueue(start)
        step_index = 0

        while not queue.is_empty():
            current = queue.dequeue()
            order.append(current)
            steps.append(
                GraphTraversalStep(
                    step=step_index,
                    action="VISIT",
                    node_id=current,
                    visited_order=list(order),
                    frontier=queue.to_list(),
                )
            )
            step_index += 1

            for neighbor in self._adjacency_list[current].neighbors:
                if neighbor not in visited:
                    visited.add(neighbor)
                    queue.enqueue(neighbor)
                    steps.append(
                        GraphTraversalStep(
                            step=step_index,
                            action="DISCOVER",
                            node_id=neighbor,
                            visited_order=list(order),
                            frontier=queue.to_list(),
                            edge=(current, neighbor),
                        )
                    )
                    step_index += 1

        result = GraphTraversalResult("BFS", start, order, steps)
        self._last_operation = {
            "operation": "BFS",
            "startNodeId": start,
            "visitedCount": len(order),
            "order": list(order),
        }
        return result

    def degree(self, node_id: Any) -> int:
        """Return outgoing degree for a node."""
        normalized_id = self._validate_start_node(node_id)
        return self._adjacency_list[normalized_id].degree()

    def in_degree(self, node_id: Any) -> int:
        """Return incoming degree for a node."""
        normalized_id = self._validate_start_node(node_id)
        total = 0
        for node in self._adjacency_list.values():
            if normalized_id in node.neighbors:
                total += 1
        return total

    def connected_components_count(self) -> int:
        """
        Return weak connectivity components count.

        For directed prerequisite graphs, this treats edges as undirected only
        for connectivity metrics. Traversals remain directed.
        """
        if self.is_empty():
            return 0

        visited: set[str] = set()
        components = 0
        for node_id in self._adjacency_list:
            if node_id in visited:
                continue
            components += 1
            stack = [node_id]
            while stack:
                current = stack.pop()
                if current in visited:
                    continue
                visited.add(current)
                for neighbor in self._undirected_neighbors(current):
                    if neighbor not in visited:
                        stack.append(neighbor)
        return components

    def edges(self) -> list[dict[str, str]]:
        """Return all graph edges as source/target dictionaries."""
        result: list[dict[str, str]] = []
        seen: set[tuple[str, str]] = set()
        for source, node in self._adjacency_list.items():
            for target in node.neighbors:
                if not self._directed:
                    edge_key = tuple(sorted((source, target)))
                    if edge_key in seen:
                        continue
                    seen.add(edge_key)
                result.append({"source": source, "target": target})
        return result

    def nodes(self) -> list[GraphNode]:
        """Return graph nodes in insertion order."""
        return list(self._adjacency_list.values())

    def to_dict(self) -> dict[str, Any]:
        """Serialize complete graph state."""
        return {
            "directed": self._directed,
            "verticesCount": self.vertices_count,
            "edgesCount": self.edges_count,
            "connectedComponents": self.connected_components_count(),
            "nodes": [node.to_dict() for node in self.nodes()],
            "edges": self.edges(),
            "lastOperation": self.last_operation,
        }

    def _validate_start_node(self, node_id: Any) -> str:
        normalized_id = self._normalize_node_id(node_id)
        if normalized_id not in self._adjacency_list:
            raise ValueError("START_NODE_NOT_FOUND")
        return normalized_id

    def _undirected_neighbors(self, node_id: str) -> list[str]:
        neighbors = list(self._adjacency_list[node_id].neighbors)
        for source, node in self._adjacency_list.items():
            if node_id in node.neighbors and source not in neighbors:
                neighbors.append(source)
        return neighbors

    @staticmethod
    def _normalize_node_id(node_id: Any) -> str:
        if node_id is None:
            raise ValueError("NODE_ID_REQUIRED")
        normalized_id = str(node_id).strip()
        if not normalized_id:
            raise ValueError("NODE_ID_REQUIRED")
        return normalized_id
